### ISSUE TITLE
[Clarification] is ScanSet required?

### ISSUE THREAD

**Issue by yundb** [penberg/mvcc-rs#56]
Hi,
the optimistic transaction in paper contains 3 sets: ReadSet / WriteSet / ScanSet, I only see ReadSet / WriteSet here, is ScanSet not needed for the implementation? 

Thanks.

**Comment by penberg** [comment]
The scan set is used by the Hekaton algorithm to protect from phantoms during a scan. We currently implement `scan()` inefficiently by taking a snapshot of the row IDs. Of course, once we improve the implementation to perform better, we will need scan set during validation.

**Comment by yundb** [comment]
Hi @penberg, by doing snapshot of row id, is it still serializable or it is snapshot isolation?

**Comment by penberg** [comment]
It's snapshot isolation. That's what we're targeting at the moment, but I realized we're not explicit about that. Opened a tracking issue as a reminder: https://github.com/penberg/mvcc-rs/issues/57
